# Site settings
title: "アースシーウィザード代表　佐々木 翔太 Resume"
# description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "佐々木 翔太 / Syota Sasaki"
resume_title:                   "ソフトウェア開発事業　アースシーウィザード 代表 <br> Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "syota.sasaki@earthsea-wizard.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "070-8587-8274"
resume_contact_address:         "東京都新宿区在住 / Shinjuku-ku, Tokyo"

resume_header_contact_info:        "syota.sasaki★earthsea-wizard.com"
resume_header_contact_info_suffix: "'★'マークを'@'に置き換えてください / Replace '★' into '@'."
resume_header_contact_telephone:   "070-8587-8274"
resume_header_contact_address:     "東京都新宿区在住 / Shinjuku-ku, Tokyo"
display_header_contact_info:       "true"

resume_header_intro: "<p>アースシーウィザード代表の佐々木は<ul><li>画像処理、画像解析、画像認識</li><li>点群データ解析</li><li>地理情報システム</li></ul>に関する技術分野で課題を抱えたお客さまへの技術協力を行うソフトウェアエンジニアとして活動を行っています。<br>I am working as freelance software engineer in image processing, point cloud data analysis, geographic information system.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/s-sasaki-earthsea-wizard"
  resume_twitter_url:           "https://twitter.com/SaMeGiraffe_VRC"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://s-sasaki-earthsea-wizard.github.io/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
